### ISSUE TITLE
In some app the Activate Func doesn't Called

### ISSUE THREAD

**Issue by ZeroIme** [nathancorvussolis/tsf-sample-ime-win7#1]
hi, may I ask a question.
In winui\input\tsf\textservice\textservice-step06-1。 In vs2017 app ,when I switch to my-ime. the icon changed ,bug Func "Activate" doesn't called.In chome,when I switch to my-ime, I works. 
thanks.

**Comment by nathancorvussolis** [comment]
**This repository is forked from**
https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples

---

There are several possible causes.

1. Chrome process is x64, but IME is x86. You should build both x64 and x86.

2. Your code maybe fails [ITfInputProcessorProfiles::AddLanguageProfile](https://docs.microsoft.com/en-us/windows/win32/api/msctf/nf-msctf-itfinputprocessorprofiles-addlanguageprofile) method.

3. Chrome maybe calls only [ITfTextInputProcessorEx::ActivateEx](https://docs.microsoft.com/en-us/windows/win32/api/msctf/nf-msctf-itftextinputprocessorex-activateex) method, but don't calls [ITfTextInputProcessor::Activate](https://docs.microsoft.com/en-us/windows/win32/api/msctf/nf-msctf-itftextinputprocessor-activate) method.

The source codes in this repository are very ancient.
For recent environment, try to read these documents.

* [Text Services Framework](https://docs.microsoft.com/en-us/windows/win32/tsf/text-services-framework)

* [Custom Input Method Editor (IME) requirements](https://docs.microsoft.com/en-us/windows/uwp/design/input/input-method-editor-requirements)

* [Third-party input method editors](https://docs.microsoft.com/en-us/windows/compatibility/third-party-input-method-editors)
